### ISSUE TITLE
Dark panel in XFCE

### ISSUE THREAD

**Issue by jcarnat** [B00merang-Project/Windows-10-Acrylic#3]
Hello,

It seems using this (Windows-10-Acrylic-5.1) GTK theme with XFCE 4.16 keeps the panel dark.
Is there a way to get a light colored panel?

Thank you.

**Comment by Elbullazul** [comment]
hello,

the panel should be white, I think I may have forgotten to update the colors. I'll update in the coming days

**Comment by Elbullazul** [comment]
d38026373161ecc1da593b9f895e481523ad4e3e fixes this
